// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config'
import { defineConfig } from 'prisma/config'

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'npx tsx prisma/seed.ts'
  },
  datasource: {
    // Fallback to dummy URL for build/generate steps where env might be missing
    url: process.env.DATABASE_URL ?? 'postgresql://postgres:postgres@localhost:5432/agora'
  }
})
